### ISSUE TITLE
Any fixes ?

### ISSUE THREAD

**Issue by sangampandasp9** [jensb89/trakt---letterboxd-import#11]
![IMG_20210513_231510_393_1](https://user-images.githubusercontent.com/46146023/118204632-4ca8b000-b47c-11eb-9500-2efbfb533309.jpg)

**Comment by jensb89** [comment]
The error indicates that the letterboxd file was not specified. Make sure to call the script like this:

`python py-trakt-letterboxd-import.py diary.csv`

Just running the script without specifying a file to load from will not work.

**Comment by sangampandasp9** [comment]
> The error indicates that the letterboxd file was not specified. Make sure to call the script like this:
> 
> `python py-trakt-letterboxd-import.py diary.csv`
> 
> Just running the script without specifying a file to load from will not work.

Doing that gives syntax error.

**Comment by jensb89** [comment]
what python version do you have?

**Comment by sangampandasp9** [comment]
> what python version do you have?

Actually I used v3 at first , but later realised that it's old so installed py v2.7 and tried in it

**Comment by jensb89** [comment]
Ok, python 2.7 should work, I used 2.7.16 as well. At some point I may upgrade the script to v3, but I haven't used it for a while and currently I don't have time for it.

Calling it with the filename should not give any syntax error. 

I will retry at my machine when I find some time, but it seems to work for others as well. Could it be that it uses your python 3 installation when you run it with python py-trakt-letterboxd-import.py diary.csv instead of your python 2 installation?
