### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by mustafadakhel** [jensb89/trakt---letterboxd-import#20]
**There are currently multipls issues with this script**

main issue was that urllib.quote_plus has been moved to urllib.parse.quote_plus, after changing that, i couldn't get authentication to work with imdb enabled, no matter what, tried deleting the app from trakt and generating a new client id and secret, generating a new pin, but nothing worked, it always throws a 401 error, i had to disable the imdb check to get it working.

**Comment by jensb89** [comment]
Thanks for opening the issue, haven't had a look at this script for a while.

First of all: Authentication is independent of the imdb enabled or disabled flag. That being said, your steps of deleting the app and generating a new pin were already right (usually only generating a new pin is enough). Since that didn't work for you, try also to delete the "auth.json" in the folder of the script if the file is already created. It might be there is already a file and the script tries to use the "old" info to get a new refresh token. Simply delete the json file and the script will do a complete new authentication. It worked for me with python 3.10

I noticed 1-2 small bugs in the script as well, also with the imdb checks (it seems the trakt api side is changed as well and expects a "imdb:id" instead of "imdb_id:id", currently any imdb info would be ignored.

 I will upload a fixed version in the next 30min or so.
