### ISSUE TITLE
Cannot get the OAuth to work

### ISSUE THREAD

**Issue by brianlehr** [jensb89/trakt---letterboxd-import#3]
This may just be a problem with me and not the program itself.

I am always failing the authentication checks, when I try to use the PIN code (which I get from clicking the "Authorize" button in the OAuth section from the Redirect URI section of the custom user-created Letterboxd import app).  Is there another code I should be using?  Has the backend Trakt code changed?

**Comment by jensb89** [comment]
The PIN Code should be all that you need. A few weeks ago at least it still worked for me. I will check on the weekend. You could try deleting your auth.json (if you have used the the import before already) and try again with a new PIN Code maybe. I will have a look, if there is something changed on PIN authorization via Trakt.

**Comment by jensb89** [comment]
Ok, I just tried. Even though there is a new authentication method on trakt (device authentication), the process with the PIN still works. 
If you still have problems try this:
1. Delete the auth.json file in your folder
2. Delete the app on trakt and create a new one
3. Fill in "urn:ietf:wg:oauth:2.0:oob" as redirect uri
4. Click the Authorize Button in the Oauth section
5. Fill in all 3 codes (client id + secret + pin) in the python file
6. exectue the program ($ python py-trakt-letterboxd-import.py diary.csv)

In the future I will implement the device authentication, since at some point trakt will probably don't offer the PIN authentication anymore. But for now, it should still be ok

**Comment by brianlehr** [comment]
Deleting the app indeed fixed the issue, thanks again!
